(function() {var implementors = {};
implementors['ethcore_rpc'] = ["impl <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for ServerHandler",];implementors['parity'] = ["impl <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for ServerHandler","impl&lt;T&gt; <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for PageHandler&lt;T&gt; <span class='where'>where T: 'static + WebApp</span>","impl <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for Redirection","impl <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for UnauthorizedHandler","impl <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for AuthRequiredHandler","impl&lt;A&gt; <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for Router&lt;A&gt; <span class='where'>where A: 'static + Authorization</span>","impl <a class='trait' href='https://hyperium.github.io/hyper/hyper/server/trait.Handler.html' title='hyper::server::Handler'>Handler</a>&lt;<a class='struct' href='https://hyperium.github.io/hyper/hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>&gt; for RestApiHandler",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
