[package]
name = "ethjson"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
build = "build.rs"

[dependencies]
ethcore-util = { path = "../util" }
rustc-serialize = "0.3"
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = { version = "0.7.0", optional = true }
clippy = { version = "0.0.69", optional = true}

[build-dependencies]
serde_codegen = { version = "0.7.0", optional = true }
syntex = "0.32.0"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]
